src/jc/urls.py
from .views import all_bands, band_info, song_info, song_filter, album_info, create_comment, person_info, song_playlist, all_songs, search
from django.urls import path, include

app_name = 'jc'

urlpatterns = [
    path('', all_bands, name='all_bands'),
    path('band_info/<int:band_id>', band_info, name = 'band_info'),
    path('song_info/<int:song_id>', song_info, name = 'song_info'),
    path('song_filter/<int:genre_id>', song_filter, name='song_filter'),
    path('album_info/<int:album_id>', album_info, name = 'album_info'),
    path('create_comment/', create_comment, name='create_comment'),
    path('person/<int:person_id>', person_info, name= 'person_info'),
    path('playlist/<int:band_id>', song_playlist, name='song_playlist'),
    path('playlist/', all_songs, name = 'all_songs'),
    path('search_result/', search, name = 'search')
]

src/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jc.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/jc/models.py
from django.db import models

# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=30, verbose_name = 'жанр')
    description = models.TextField(max_length=2000, verbose_name = 'описание', blank=True, null=True)

    class Meta:
        verbose_name = 'жанр'
        verbose_name_plural = 'жанры'

    def __str__(self):
        return f'{self.name}'


class Band(models.Model):
    image = models.ImageField(upload_to='images', blank=True)
    name = models.CharField(max_length=50, verbose_name='название группы')
    description = models.TextField(max_length=2000, verbose_name = 'описание')

    class Meta:
        verbose_name = 'группа'
        verbose_name_plural = 'группы'
    
    def __str__(self):
        return f"{self.name}"

class Person(models.Model):
    image = models.ImageField(upload_to='images', blank=True)
    name = models.CharField(max_length=50, verbose_name = 'имя')
    last_name = models.CharField(max_length=50, verbose_name = 'фамилия')
    instrument = models.CharField(max_length=30, verbose_name = 'инструмент')
    band = models.ForeignKey(Band, on_delete=models.CASCADE)
    info = models.TextField(max_length=2000, blank=True, null=True)

    class Meta:
        verbose_name = 'участник'
        verbose_name_plural = 'участники'

    def __str__(self):
        return f"{self.name, self.last_name}"   

class Album(models.Model):
    image = models.ImageField(upload_to='images', blank=True)
    name = models.CharField(max_length=100, verbose_name = 'название альбома')
    band = models.ForeignKey(Band, related_name='albums', on_delete = models.CASCADE)
    description = models.TextField(max_length=2000, verbose_name='описание', null=True)
    
    class Meta:
        verbose_name = "альбом"
        verbose_name_plural = "альбомы"

    def __str__(self):
        return f"{self.name}"


class Song(models.Model):
    name = models.CharField(max_length=100, verbose_name = 'название песни')
    genre = models.ManyToManyField(Genre, max_length=200, verbose_name = 'жанр')
    lyrics = models.TextField(max_length=3000, verbose_name = 'текст')
    album = models.ForeignKey(Album, on_delete = models.CASCADE)
    description = models.TextField(max_length=4000, verbose_name = 'описание', blank=True, null=True)
    audio_file = models.FileField(upload_to='music', blank=True, null=True)
    
    class Meta:
        verbose_name = 'песня'
        verbose_name_plural = 'песни'
    
    def __str__(self):
        return f"{self.name}"



class Comment(models.Model):
    author = models.CharField(max_length = 50, verbose_name='автор')
    text = models.TextField(max_length=500, verbose_name='текст')
    
    class Meta:
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарии'
    
    def __str__(self):
        return f"{self.author}"
    

src/jc/forms.py
from django import forms 
from .models import Comment

class CreateCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'

src/jc/views.py
import requests
import datetime
from django.shortcuts import render, redirect
from .models import Person, Song, Band, Genre, Album, Comment
from jc.forms import CreateCommentForm
from django.conf import settings

#   BANDS
def get_core_html_data():
    genres = Genre.objects.all()
    bands = Band.objects.all()
    now = datetime.datetime.now()
    time = now.strftime("%d-%m-%Y %H:%M")
    return {'bands':bands, 'genres':genres, 'time':time}

def all_bands(request):
    bands = Band.objects.all()
    songs = Song.objects.all()
    return render(request, 'all_bands.html', {'dropdown': get_core_html_data(), 'songs':songs, 'bands':bands})

def band_info(request, band_id):
    band = Band.objects.get(id = band_id)
    members = Person.objects.filter(band = band_id)   
    albums = Album.objects.filter(band = band_id)
    return render(request, 'band_info.html', {'band':band, 'albums':albums, 'members':members, 'dropdown': get_core_html_data()})

#   SONGS
def song_playlist(request, band_id):
    songs = Song.objects.filter(album__band_id = band_id)
    all_songs = Song.objects.all()
    return render(request, 'playlist.html', {'songs':songs, 'all_songs':all_songs, 'dropdown': get_core_html_data()})

def all_songs(request):
    songs = Song.objects.all()
    return render(request, 'playlist.html', {'songs':songs, 'dropdown': get_core_html_data()})
    
def song_info(request, song_id):
    song_inf = Song.objects.filter(id=song_id)
    return render(request, 'song_info.html', {'song_inf':song_inf, 'dropdown': get_core_html_data()})

def song_filter(request, genre_id):
    songs = Song.objects.filter(genre = genre_id)
    genre = Genre.objects.get(id = genre_id)
    return render(request, 'song_filter.html', {'songs':songs, 'genre':genre, 'dropdown': get_core_html_data()})

def album_info(request, album_id):
    songs = Song.objects.filter(album = album_id)
    album = Album.objects.get(id=album_id)
    return render(request, 'album_info.html', {'songs':songs, 'album':album, 'dropdown': get_core_html_data()})    

#Create comment
def create_comment(request):
    form = CreateCommentForm()
    if request.method == 'POST':
        author = request.POST.get('author')
        text = request.POST.get('text')
        save_form = CreateCommentForm(request.POST)
        if save_form.is_valid():
            note = save_form.save(commit=False)
            note.save()
            print(settings.URL+'author'+'text')
            res = requests.get(settings.URL+f'{author}\n{text}')
            print(res)
            return redirect('jc:all_bands')
    return render(request, 'create_comment.html', {'form':form, 'dropdown': get_core_html_data() })


#   persons

def person_info(request, person_id):
    person = Person.objects.get(id = person_id)
    return render(request, 'person_info.html', {'person':person, 'dropdown': get_core_html_data()})

# search
def search(request):
    query = request.GET.get('q')
    bands = Band.objects.filter(name__icontains=query)
    songs = Song.objects.filter(name__icontains=query)
    return render(request, 'search_result.html', {'bands':bands, 'songs':songs})

src/jc/templates/album_info.html
{% extends 'core.html' %}
{% block content %}
<style>
  .verse {
    display: table;
    margin: 0 auto; /* для центрирования display: table; не нужно указывать ширину блока, она рассчитывается самостоятельно */ 
    white-space: pre-line; /* не нужен <br> */ 
    word-wrap: break-word; /* чтобы слова переносились на маленьком экране */ 
  }
  </style>
<div class="card"   style="max-width: 1000px; background-color: rgb(80, 80, 80); margin: 0 auto;">
  <img src="{{album.image.url}}" class="card-img-top" alt="...">
    <h5 class="card-header text-white">{{album.name}}</h5>
    <div class="card-body">
      <p class="verse card-text text-white">{{album.description}}</p>
      <h5 class="text-white">Песни альбома</h5>
      {% for song in songs %}
      <p>
      <a href="{% url 'jc:song_info' song_id=song.id %}" class="btn btn-black text-white">{{song.name}}</a>
      </p>
      {% endfor %}
    </div>
  </div>
{% endblock %}

src/jc/templates/all_bands.html
{% extends 'core.html' %}
{% block content %}
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel" style="max-width: 1100px; margin: 0 auto; margin-top: 1%;">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Skillet_Press_Photo_001.jpg/1200px-Skillet_Press_Photo_001.jpg" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://www.soyuz.ru/public/uploads/files/2/7459315/202103081637034bec6df1c9.jpg" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://www.metalsucks.net/wp-content/uploads/2020/06/Tommy-Vext-2019-Wikipedia-Creative-Commons-1280x720.jpg" class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
<p></p>
<style>
  .card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    padding: 16px;
    text-align: center;
    width: 20rem;
    background-color:rgb(80, 80, 80);
    margin-left: 10%; 
    margin-top: 5%;
    transition: background-color 0.5s linear;
  }
  .card-container {
      display: grid;
      padding: 1rem;
      grid-template-columns: repeat(3, minmax(320px, 1fr));
      grid-gap: 1rem; 
  }
  .card:hover {
          background-color: rgb(48, 47, 47);
        }
  
  </style>

<section class="card-container">
  {% for band in bands %}
  <div class="card" >
    <img src="{{band.image.url}}" class="card-img-top" alt="...">
    <div class="card-body">
      <p class="card-text text-white">{{band.name}}</p>
      <a href="{% url 'jc:band_info' band_id=band.id %}" class="btn btn-black text-white">more info</a>
    </div>
  </div>
  {% endfor %}
</section>
{% endblock %}

src/jc/templates/band_info.html
{% extends 'core.html' %}
{% block content %}
<style>
  .verse {
    display: table;
    margin: 0 auto; /* для центрирования display: table; не нужно указывать ширину блока, она рассчитывается самостоятельно */ 
    white-space: pre-line; /* не нужен <br> */ 
    word-wrap: break-word; /* чтобы слова переносились на маленьком экране */ 
  }
  </style>
<p></p>
<div class="card mb-3"  style="max-width: 1000px; background-color: rgb(80, 80, 80); margin: 0 auto; margin-top: 1%;">
    <img src="{{band.image.url}}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title text-white">{{band.name}}</h5>
      <p class="verse card-text text-white">{{band.description}}</p>
      <p></p>
      <h5 class="card-text text-white">Члены группы</h5>
    {% for person in members %}
      <p>
        <a class="btn btn-black text-white" href="{% url 'jc:person_info' person_id=person.id %}">{{person.name}} {{person.last_name}} - {{person.instrument}}</a>
      </p>
    {% endfor %}
    <h5 class="card-text text-white">Альбомы группы</h5>
    {% for album in albums %}
    <p>
      <a class="btn btn-black text-white" href="{% url 'jc:album_info' album_id=album.id %}">{{album.name}}</a>
    </p>  
    {% endfor %}
    </div>
  </div>
{% endblock %}

src/jc/templates/core.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
      .dropbtn {
        background-color: #4CAF50;
        color: white;
        padding: 16px;
        font-size: 16px;
        border: none;
      }
      
      .dropdown {
        position: relative;
        display: inline-block;
      }
      
      .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
      }
      
      .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
      }
      
      .dropdown-content a:hover {background-color: #ddd;}
      
      .dropdown:hover .dropdown-content {display: block;}
      
      .dropdown:hover .dropbtn {background-color: #3e8e41;}
      </style>
</head>
<header>
   </style>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <style>.logo-image{
            width: 46px;
            height: 46px;
            border-radius: 50%;
            overflow: hidden;
            margin-top: -6px;
        }</style>
          <a class="navbar-brand">
            <div class="logo-image">
                  <img src="https://46.cdn.ekm.net/ekmps/shops/094f03/images/rock-horns-[2]-17116-1-p.jpg?w=768&h=768&v=1" class="img-fluid">
            </div>
          </a>
          <a class="navbar-brand">Rock.msc</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{% url 'jc:all_bands' %}">Home</a>
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <div class="dropdown">
                    <button class="btn btn-dark dropdown-toggle">Bands</button>
                    <div class="dropdown-content">
                      {% for band in dropdown.bands %}
                      <li><a class="dropdown-item" href="{% url 'jc:band_info' band_id=band.id %}">{{band.name}}</a></li>
                      {% endfor %}
                    </div>
                  </div>
                  <p></p>
                  <ul class="navbar-nav">
                    <div class="dropdown">
                        <button class="btn btn-dark dropdown-toggle">Genres</button>
                        <div class="dropdown-content">
                          {% for genre in dropdown.genres %}
                          <li><a class="dropdown-item" href="{% url 'jc:song_filter' genre_id=genre.id %}">{{genre.name}}</a></li>
                          {% endfor %}
                        </div>
                      </div>
                   <div class="dropdown">
                    <button class="btn btn-dark dropdown-toggle">Songs</button>
                    <div class="dropdown-content">
                      <li><a class="dropdown-item" href="{% url 'jc:all_songs' %}">All</a></li>
                      {% for band in dropdown.bands %}
                      <li><a class="dropdown-item" href="{% url 'jc:song_playlist' band_id=band.id %}">{{band.name}}</a></li>
                      {% endfor %}
                    </div>
                  </div>  
            </div>
          </div>
          <form action="{% url 'jc:search' %}" method="get">
            <input name="q" type="text" placeholder="Search...">
          </form>
        </div>
      </nav>
</header>
<body>
  <style>
    body {
      background-image: url('https://thumb.tildacdn.com/tild6263-3531-4732-b661-396338643061/-/format/webp/Frame_4.png');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }
    </style>
    <div class="wrapper">
      <div class="sub"></div>
        {% block content %}
        {% endblock %}
    </div>
</body>
<p></p>
<!-- Footer -->
<footer class="bg-dark text-center text-lg-start">
  <!-- Grid container -->
  <div class="container p-4">
    <!--Grid row-->
    <div class="row">
      <!--Grid column-->
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0 text-white">
        <h5 class="text-uppercase">Footer Content</h5>

        <p>
          Мой тестовый проект <br>
          Здесь может быть ваша реклама
        </p>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0 text-white">
        <h5 class="text-uppercase white">Links</h5>

        <ul class="list-unstyled mb-0">
          <li>
            <a href="{% url 'jc:create_comment' %}" class="text-white">leave a comment</a>
          </li>
          <li>
            <a href="#" class="text-white">Link 2</a>
          </li>
          <li>
            <a href="#!" class="text-white">Link 3</a>
          </li>
          <li>
            <a href="#!" class="text-white">Link 4</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase mb-0 text-white">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!" class="text-white">Link 1</a>
          </li>
          <li>
            <a href="#!" class="text-white">Link 2</a>
          </li>
          <li>
            <a href="#!" class="text-white">Link 3</a>
          </li>
          <li>
            <a href="#!" class="text-white">Link 4</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
  <!-- Grid container -->
  <!-- Copyright -->
  <div class="text-center p-3 text-white" style="background-color: rgba(0, 0, 0, 0.2);">
    {{dropdown.time}}
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->
</html>

src/jc/templates/create_comment.html
{% extends 'core.html' %}
{% block content %}
<form method="post" class='text-white' style="margin-left: 10%; margin-top: 5%;"> {% csrf_token %}
  <p>Автор</p>
    {{form.author}}
    <p></p>
  <p>Комментарий</p>
    {{form.text}}
    <button class ="btn btn-dark" type="sumbit" >отправить</button>
  </form>
{% endblock %}

src/jc/templates/person_info.html
{% extends 'core.html' %}
{% block content %}
<style>
    .verse {
      display: table;
      margin: 0 auto; /* для центрирования display: table; не нужно указывать ширину блока, она рассчитывается самостоятельно */ 
      white-space: pre-line; /* не нужен <br> */ 
      word-wrap: break-word; /* чтобы слова переносились на маленьком экране */ 
    }
    </style>
  <div class="card"   style="max-width: 1000px; background-color: rgb(80, 80, 80); margin: 0 auto;">
    <img src="{{person.image.url}}" class="card-img-top" alt="...">
      <h5 class="card-header text-white">{{person.name}} {{person.last_name}}</h5>
      <div class="card-body">
        <p class="verse card-text text-white">{{person.info}}</p>
        <p></p>
        <h5 class="text-white">Инструмет</h5>
        <p class="btn btn-black text-white">{{person.instrument}}</p>
      </div>
    </div>
{% endblock %}

src/jc/templates/playlist.html
{% extends 'core.html' %}
{% block content %}
{% for song in songs %}
<style>
.song{
  max-width: 1000px;
  background-color: rgb(80, 80, 80); 
  margin: 0 auto;
  transition: background-color 0.5s linear;
}

.song:hover {
          background-color: rgb(48, 47, 47);
        }
</style>
<div class="song">
    <h5 class="card-header text-white">{{song.album.band}} - {{song.album}}</h5>
    <div class="card-body">
      <h5 class="card-title text-white">{{song.name}}</h5>
      <audio controls>
        <source src="{{ song.audio_file.url }}" type="audio/mpeg">
    </audio>
    <a href="{% url 'jc:song_info' song_id=song.id %}" class="btn btn-dark">more info</a>
    </div>
  </div> 
  <p></p>
{% endfor %}
{% endblock %}

src/jc/templates/search_result.html
{% extends 'core.html' %}
{% block content %}
<h1 class='text-white' style="margin-left: 100px;">Search Results</h1>
<style>
    .card {
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
      padding: 16px;
      text-align: center;
      width: 20rem;
      background-color:rgb(80, 80, 80);
      margin-left: 10%; 
      margin-top: 5%;
      transition: background-color 0.5s linear;
    }
    .card-container {
        display: grid;
        padding: 1rem;
        grid-template-columns: repeat(3, minmax(320px, 1fr));
        grid-gap: 1rem; 
    }
    .card:hover {
            background-color: rgb(48, 47, 47);
          }
    
    </style>

<section class="card-container">
    {% for band in bands %}
    <div class="card" >
      <img src="{{band.image.url}}" class="card-img-top" alt="...">
      <div class="card-body">
        <p class="card-text text-white">{{band}}</p>
        <a href="{% url 'jc:band_info' band_id=band.id %}" class="btn btn-black text-white">more info</a>
      </div>
    </div>
    {% endfor %}
  </section>

<style>
.song{
  max-width: 1000px;
  background-color: rgb(80, 80, 80); 
  margin: 0 auto;
  transition: background-color 0.5s linear;
}

.song:hover {
          background-color: rgb(48, 47, 47);
        }
</style>
{% for song in songs %}
<div class="song">
    <h5 class="card-header text-white">{{song.album.band}} - {{song.album}} </h5>
    <div class="card-body">
      <h5 class="card-title text-white">{{song.name}}</h5>
      <audio controls>
        <source src="{{ song.audio_file.url }}" type="audio/mpeg">
    </audio>
      <a href="{% url 'jc:song_info' song_id=song.id %}" class="btn btn-dark">more info</a>
    </div>
  </div> 
  <p></p>
{% endfor %}

{% endblock %}

src/jc/templates/song_filter.html
{% extends 'core.html' %}
{% block content %}
<p></p>
<style>
.song{
  max-width: 1000px;
  background-color: rgb(80, 80, 80); 
  margin: 0 auto;
  transition: background-color 0.5s linear;
}

.song:hover {
          background-color: rgb(48, 47, 47);
        }
</style>

<div class="card"   style="max-width: 1000px; background-color: rgb(80, 80, 80); margin: 0 auto;">
    <h5 class="card-header text-white">{{genre.name}}</h5>
    <div class="card-body">
      <p class="verse card-text text-white">{{genre.description}}</p>
    </div>
  </div>
<p></p>

{% for song in songs %}
<div class="song">
    <h5 class="card-header text-white">{{song.album.band}} - {{song.album}} </h5>
    <div class="card-body">
      <h5 class="card-title text-white">{{song.name}}</h5>
      <audio controls>
        <source src="{{ song.audio_file.url }}" type="audio/mpeg">
    </audio>
      <a href="{% url 'jc:song_info' song_id=song.id %}" class="btn btn-dark">more info</a>
    </div>
  </div> 
  <p></p>
{% endfor %}
{% endblock %}

src/jc/templates/song_info.html
{% extends 'core.html' %}
{% block content %}
{% for song in song_inf %}
<p></p>
<div class="card" style="max-width: 1000px; margin: 0 auto; border-color:rgb(80, 80, 80);">
    <h5 class="card-header text-white" style="background-color:rgb(80, 80, 80);">{{song.name}}</h5>
    <div class="card-body">
      <p class="card-title">{{song.description}}</p>
      <h5 class="card-title">Жанры песни</h5>
      {% for genre in song.genre.all %}
      <p><a class='btn btn-black text-black' href = "{% url 'jc:song_filter' genre_id=genre.id %}">{{genre}}</a></p>
      {% endfor %}
      <style>
      audio { width: 70%;
        margin: 0 auto }
      </style>
      <audio controls>
        <source src="{{ song.audio_file.url }}" type="audio/mpeg">
    </audio>
      <style>
        .verse {
          display: table;
          margin: 0 auto; /* для центрирования display: table; не нужно указывать ширину блока, она рассчитывается самостоятельно */ 
          white-space: pre-line; /* не нужен <br> */ 
          word-wrap: break-word; /* чтобы слова переносились на маленьком экране */ 
        }
        </style>
      <p class="verse">{{song.lyrics}}</p>
    </div>
  </div>
{% endfor %}
{% endblock %}